name: Update database
on:
  workflow_dispatch:
    inputs:
      link:
        description: "JSON representation of a saved link"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update item list
        run: python ./.github/workflows/build_json.py "${{ github.event_path }}"
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes
        if: ${{ !env.ACT }}
        run: git status
      - name: Stage changes
        if: ${{ !env.ACT }}
        run: git add .
      - name: Commit changes
        if: ${{ !env.ACT }}
        run: |
          git config user.name "BeerLonerds website auto updater"
          git config user.email "<>"
          git commit -m "Auto updating db.json"
      - name: Push changes
        if: ${{ !env.ACT }}
        run: git push origin main
