name: Build item list
on:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install -r ./.github/workflows/requirements.txt
      - name: Update item list
        run: python ./.github/workflows/get_data.py
      - name: Check for changes
        run: git status
      - name: Stage changes
        run: git add .
      - name: Commit changes
        run: |
          git config user.name "BeerLonerds website auto updater"
          git config user.email ${{ secrets.AONNGHUS_COMMIT_EMAIL }}
          git commit -m "Auto updating index.html"

      - name: Push changes
        run: git push origin main